package com.del.potplayercontrol.impl;

public class JNAMessageConst {
   public static final int PLAY = 20001;
   public static final int PAUSE = 20000;
   public static final int STOP = 20002;
   public static final int PREVIOUS = 10123;
   public static final int NEXT = 10124;
   public static final int PLAY_PAUSE = 10014;
   public static final int VOLUME_UP = 10035;
   public static final int VOLUME_DOWN = 10036;
   public static final int TOGGLE_MUTE = 10037;
   public static final int TOGGLE_SUBS = 10126;
   public static final int TOGGLE_OSD = 10351;
   public static final int FIVE_SEC_BACK = 10059;
   public static final int FIVE_SEC_FORWARD = 10060;
   public static final int THIRTY_SEC_BACK = 10061;
   public static final int THIRTY_SEC_FORWARD = 10062;
   public static final int ONE_MIN_BACK = 10063;
   public static final int ONE_MIN_FORWARD = 10064;
   public static final int FIVE_MIN_BACK = 10065;
   public static final int FIVE_MIN_FORWARD = 10066;
   public static final int SPEED_NORMAL = 10246;
   public static final int SPEED_DOWN = 10247;
   public static final int SPEED_UP = 10248;
   public static final int FULLSCREEN = 10013;
   public static final int GET_VOLUME = 20480;
   public static final int SET_VOLUME = 20481;
   public static final int GET_TOTAL_TIME = 20482;
   public static final int GET_PROGRESS_TIME = 20483;
   public static final int GET_CURRENT_TIME = 20484;
   public static final int SET_CURRENT_TIME = 20485;
   public static final int GET_PLAY_STATUS = 20486;
   public static final int SET_PLAY_STATUS = 20487;
   public static final int SET_PLAY_ORDER = 20488;
   public static final int SET_PLAY_CLOSE = 20489;
   public static final int CAPTURE = 10224;
   public static final int TOGGLE_PLAYLIST = 10011;
   public static final int TOGGLE_CONTROL = 10383;
   public static final int OPEN_FILE = 10158;
   public static final int SEND_VIRTUAL_KEY = 20496;
}
